### ISSUE TITLE
DMains -  Draft Scenario l View (Developer) Diagram part of the 4+1 requirement due by week 3

### ISSUE THREAD

**Issue by 1jc** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#19]

**Comment by kdpcapstone** [comment]
The diagram needs updating, but we're bypassing per Kyle's instruction.  Also, There is a process diagram and developer diagram that is updated that the team can go by in the project documents link in the wiki pages

**Comment by Napomoi** [comment]
Per Kyle's instructions Efort on 4+1 should be redirected. this issue may be updated at a future date.
