### ISSUE TITLE
kkennedy-gh Draft Logical View Diagram part of the 4+1 requirement due by week 3

### ISSUE THREAD

**Issue by 1jc** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#3]
Revising Logical View UML State Diagram

**Comment by kkennedy-gh** [comment]
As a programmer, I want to develop a Logical View Diagram as part of our 4 + 1 diagram for our team project.

**Comment by kdpcapstone** [comment]
Hey Kyle, 
You're missing some steps.  
User 1 sends unencrypted data and a key to the cloud service.  The cloud service evaluates if it is unencrypted or encrypted data.  If it is unencrypted, it sends it to the service that encrypts it and sends it back to user 1.  User 1 manually sends encrypted data to user 2, and privately tells them the key.  User 2 sends the encrypted data and the key to the service.  The service determines if it is unencrypted or encrypted.  If encrypted, it validates the key against the encrypted key, and if matches, unencrypts the data and sends it back to user 2, else sends a message that the key is invalid.

**Comment by kkennedy-gh** [comment]
[Send_Data_Securely_Logical_State_Diagram_Revision_1.pdf](https://github.com/kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely/files/10460999/Send_Data_Securely_Logical_State_Diagram_Revision_1.pdf)

**Comment by kkennedy-gh** [comment]
Update diagram. Please review and comment on any possible revisions needed.

**Comment by kkennedy-gh** [comment]
[Send_Data_Securely_Logical_State_Diagram_Revision_1.pdf](https://github.com/kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely/files/10461012/Send_Data_Securely_Logical_State_Diagram_Revision_1.pdf)

**Comment by kkennedy-gh** [comment]
Update diagram. Please review and comment on any possible revisions needed.

**Comment by kkennedy-gh** [comment]
/home/kai/Desktop/Send_Data_Securely_Logical_State_Diagram_Revision_1.pdf

**Comment by kkennedy-gh** [comment]
[Send_Data_Securely_Logical_State_Diagram_Revision_1.pdf](https://github.com/kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely/files/10461056/Send_Data_Securely_Logical_State_Diagram_Revision_1.pdf)

**Comment by kkennedy-gh** [comment]
Update diagram. Please review and comment on any possible revisions needed.

**Comment by kkennedy-gh** [comment]
[logical_view_4_+_1_send_data_securely.pdf](https://github.com/kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely/files/10506672/logical_view_4_%2B_1_send_data_securely.pdf)

**Comment by kkennedy-gh** [comment]
Revision if necessary.

**Comment by kdpcapstone** [comment]
This looks like it is missing a few things still, but per Kyle, we're not updating the documents any more.  There is a process diagram per kyle's approval in the project documents in the wiki folder the team can reference.
