### ISSUE TITLE
ariunzayaE Draft Process View Diagram part of the 4+1 requirement due by week 3

### ISSUE THREAD

**Issue by 1jc** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#4]
ariunzayaE Draft Process View Diagram part of the 4+1 requirement due by week 3

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/212998978-b204cae5-e579-450b-be45-872b38bdba65.png)

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/213372526-818cba9c-1982-4817-96b5-dccd04e38a26.png)

Updated diagram

**Comment by ariunzayaE** [comment]
Updated diagram 3

https://lucid.app/lucidspark/3fdcc803-d5bb-4162-8870-d9e8adddd37f/edit?viewport_loc=-1820%2C506%2C3072%2C1427%2C0_0&invitationId=inv_744e68b0-0fc5-46ed-b32a-2dcea3f43f80



![Image](https://user-images.githubusercontent.com/81658998/214772581-41cba47d-6dd6-4e86-86d0-c6185288e8fa.png)

**Comment by ariunzayaE** [comment]
It is not current diagram.
