### ISSUE TITLE
zenwattage Draft user scenario View Diagram part of the 4+1 requirement due by week 3

### ISSUE THREAD

**Issue by 1jc** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#5]
zenwattage Draft user scenario View Diagram part of the 4+1 requirement due by week 3

**Comment by zenwattage** [comment]
![Image](https://user-images.githubusercontent.com/24535467/211394718-8d6a5bb6-f96b-48b7-bd6e-b334d9320863.png)

**Comment by 1jc** [comment]
1jc reviewed confirmed great documentation and diagram presented by zenwattage jan 9 at 12:08 pm

**Comment by kdpcapstone** [comment]
Hey Zenwattage, 

I believe you're missing a the last part of your diagram.  From my notes from what Kyle said, once the receiving user receives the encrypted message from the sending user, they send it back to the AWS Cloud service via the API, which decrypts it, and sends it back to the receiving user.

**Comment by zenwattage** [comment]
Yeah thanks I realized that after I posted it.  I'll fix it
