### ISSUE TITLE
'

### ISSUE THREAD

**Issue by 1jc** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#52]

**Comment by 1jc** [comment]
[Improve the UI screen in connection to Issue #52 user story build GUI for messages encryption/decryption /cryptography#58](https://github.com/kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely/issues/58) Issue#58
added issue#58 which is a duplicate towards issue#52    1jc will add files to issue#52

**Comment by 1jc** [comment]
**wrieframes for UI**
![image](https://user-images.githubusercontent.com/34551673/215907914-e0e84670-7e86-4d5c-a20d-568637914267.png)
![image](https://user-images.githubusercontent.com/34551673/215908096-ed7a47df-dada-4528-aecb-58e42d8fffa9.png)
![image](https://user-images.githubusercontent.com/34551673/215908371-656150bb-03b5-4f92-9755-f10e28683860.png)
![image](https://user-images.githubusercontent.com/34551673/215908510-f939e433-c761-42b9-a9ce-9928388e8ef4.png)

**Comment by 1jc** [comment]
**1jc build wire frames for UI   User story Build GUI For Messages Encryption/Decryption wireframes for UI #52**

**Comment by kdpcapstone** [comment]
Hey 1jc,
I thought Kyle said we didn't need a log in process?  I think we just need a nice looking page that displays an alphanumeric text field, an alphanumeric key field, an Encrypt button, and a Decrypt button, some instructions, and any other graphics or information that you think would make it look nice or be helpful.

**Comment by zenwattage** [comment]
These wire frames are over complicating what you actually need to do and don't seem to even match this project. You don't need to write almost any of the code you are listing here. Most of the stuff you are saying you need to write is already there. All the group wants you to do is improve the styling of what is there. Adding scrollbars, and side bars and toolbars,etc is all just seems like random stuff that is being added for no reason.
