### ISSUE TITLE
Create decryption lambda function

### ISSUE THREAD

**Issue by ariunzayaE** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#53]

**Comment by zenwattage** [comment]
Here is a working decryption function:

const crypto = require('crypto');

exports.handler = async (event) => {
  const encrypted = event.encrypted;
  let key = event.key;

  const minKeyLength = 32;
  if (key.length < minKeyLength) {
	key = key.padEnd(minKeyLength, '0');
  }

  const decrypt = (encrypted, key) => {
	const [iv, encryptedText] = encrypted.split(':').map(x => Buffer.from(x, 'hex'));
	const decipher = crypto.createDecipheriv('aes-256-cbc', Buffer.from(key), iv);
	let decrypted = decipher.update(encryptedText);
	decrypted = Buffer.concat([decrypted, decipher.final()]);
	return decrypted.toString();
  };

  const decrypted = decrypt(encrypted, key);
  return { decrypted };
};

**Comment by ariunzayaE** [comment]
This is the functional code.

import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const crypto = require('crypto');

export const handler = async (event) => {
  console.log(event)
  const encrypted = event.encrypted;
  let key = event.key;

  const minKeyLength = 32;
  if (key.length < minKeyLength) {
	key = key.padEnd(minKeyLength, '0');
  }

  const decrypt = (encrypted, key) => {
	const [iv, encryptedText] = encrypted.split(':').map(x => Buffer.from(x, 'hex'));
	const decipher = crypto.createDecipheriv('aes-256-cbc', Buffer.from(key), iv);
	let decrypted = decipher.update(encryptedText);
	decrypted = Buffer.concat([decrypted, decipher.final()]);
	return decrypted.toString();
  };

  const decrypted = decrypt(encrypted, key);
  return { decrypted };
};

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/216495185-7eba9c23-e7a5-46de-ba67-beda49b55c7e.png)
