### ISSUE TITLE
As a developer I want to learn what is cryptography and how to use it for encryption and decryption

### ISSUE THREAD

**Issue by ariunzayaE** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#67]

**Comment by ariunzayaE** [comment]
https://www.youtube.com/watch?v=NuyzuNBFWxQ 

I found this video is so helpful and informative

**Comment by kdpcapstone** [comment]
https://www.youtube.com/watch?v=NuyzuNBFWxQ
https://www.youtube.com/watch?v=KVuSC03CA4E
https://www.youtube.com/watch?v=9PL7EK4jXLM
https://www.youtube.com/watch?v=W_Gj1Q0lEOU

https://cryptojs.gitbook.io/docs/

https://www.sciencedirect.com/topics/computer-science/secret-key-encryption#:~:text=Encryption%20is%20the%20foundation%20of,to%20encrypt%20and%20decrypt%20data.

https://www.tsmean.com/articles/aws/the-ultimate-aws-lambda-tutorial-for-nodejs/

https://www.ibm.com/docs/en/sdk-java-technology/8?topic=cp-cryptographic-hash-functions-message-authentication-codes-digital-signatures

https://www.youtube.com/watch?v=hBbtvlFxUDg

https://www.youtube.com/watch?v=9PL7EK4jXLM

https://www.youtube.com/watch?v=W_Gj1Q0lEOU

https://gist.github.com/dudepare/99f4d682c3db90ea86a4331e32f0006a
