### ISSUE TITLE
As a developer, I want lambda decryption function to be invoked by Postman, or REST API

### ISSUE THREAD

**Issue by ariunzayaE** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#74]

**Comment by zenwattage** [comment]
Done via Postman.

![Image](https://user-images.githubusercontent.com/24535467/217322583-5f102743-8cbe-42a2-970d-8300d3b707b2.png)

**Comment by ariunzayaE** [comment]
![Image](https://user-images.githubusercontent.com/81658998/219534911-186c716c-ed9a-46ee-8160-86898746f0df.png)
