### ISSUE TITLE
Update front end layout to have a more informative and user friendly interface

### ISSUE THREAD

**Issue by Napomoi** [kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely#85]

**Comment by Napomoi** [comment]
initiated by Donald Mains 02/09/2023. 
An updated layout has been created but not yet deployed with help from joette Demo. 

![Image](https://user-images.githubusercontent.com/36967028/217962420-5f638197-3c39-43e1-9810-e264d84505bf.JPG)

Still need additional work

**Comment by Napomoi** [comment]
A new updated UI interface was pushed to new branch  DonaldMains02142023

**Comment by 1jc** [comment]
Scott Hansford
  [6:37 AM](https://nscad.slack.com/archives/C04H69U6HP1/p1676644627105949)
[@Joette Damo](https://nscad.slack.com/team/U755WPWTC)
 You have multiple pull requests that are duplicating the same things. For example you are pushing Header code in 2 different pull requests that is the same lines. You are also pushing changes to App.js that are the same lines in 2 different pull requests. You are also referencing multiple issues in each of these that don't actually make sense to what the code being committed is doing. For example your App.js PR is referencing 5 issues and 3 of them have nothing to do with App.js or what the lines you are trying to add would do to App.js. Lastly, the large pull request you attempted last week and are still attempting this week still has all the problematic files in it that we addressed during the slack call on Sunday.

**Comment by 1jc** [comment]
1jc See issue #122 to make updated changes for text block
